### ISSUE TITLE
Error at docker container creation with armv7 image

### ISSUE THREAD

**Issue by smike23** [SamTV12345/LIVISI-Unofficial-SmartHome-Frontend#48]
### Describe the bug

after creating the docker image with the docker-compose file (base_url, password and user of course changed) i get the following error (used armv7 image / raspberry pi):

```
thread 'main' panicked at src/utils/connection.rs:48:52:
called `Result::unwrap()` on an `Err` value: reqwest::Error { kind: Decode, source: Error("missing field `access_token`", line: 1, column: 115) }
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
after runnig with env `RUST_BACKTRACE=full` i get:
```
thread 'main' panicked at src/utils/connection.rs:48:52:
called `Result::unwrap()` on an `Err` value: reqwest::Error { kind: Decode, source: Error("missing field `access_token`", line: 1, column: 115) }

stack backtrace:
   0:   0x9a9b08 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h4be301fc8133f6d1
   1:   0x9e4b60 - core::fmt::write::h9607f026b3a1fe6a
   2:   0x9a58dc - std::io::Write::write_fmt::h6cc50c2b43e7755c
   3:   0x9a9894 - std::sys_common::backtrace::print::h7d813e8ad6243ab9
   4:   0x9ab03c - std::panicking::default_hook::{{closure}}::he30c0de6c2b68bd5
   5:   0x9aac08 - std::panicking::default_hook::h88fee80814bba16a
   6:   0x9ab774 - std::panicking::rust_panic_with_hook::h950c2f91443cd029
   7:   0x9ab41c - std::panicking::begin_panic_handler::{{closure}}::h28ff02395d3563f7
   8:   0x9aa06c - std::sys_common::backtrace::__rust_end_short_backtrace::h5825cb7b2f8c8191
   9:   0x9ab1d4 - rust_begin_unwind
  10:    0x39a8c - core::panicking::panic_fmt::h6604f07ff4b4706d
  11:    0x39f40 - core::result::unwrap_failed::h5d28c59258d941df
  12:    0xa656c - api::utils::connection::MemPrefill::get_token::{{closure}}::h87bc30765718174e
  13:    0x9f6d4 - <tokio::task::local::RunUntil<T> as core::future::future::Future>::poll::h3ea0e4b40d2274c4
  14:   0x146ab0 - tokio::runtime::scheduler::current_thread::Context::enter::h40ebfb37dba56886
  15:   0x118d0c - tokio::runtime::context::set_scheduler::h8e242b31b7ef8c14
  16:   0x145ba4 - tokio::runtime::runtime::Runtime::block_on::hbd8a928e3e4dcb6b
  17:   0x11c038 - api::main::he321d005549e5507
  18:   0x15b9b8 - std::sys_common::backtrace::__rust_begin_short_backtrace::h310ea000f6db98e0
  19:   0x139068 - std::rt::lang_start::{{closure}}::h6259daf99a878131
  20:   0x99c69c - std::rt::lang_start_internal::h11093c4ea0de06dd  21:   0x11c1a4 - main
  
```

### Reproduction

create docker-compose.yml file, change base_url, user (admin) and password and create container with 'docker compose up -d'

### System Info

```Shell
Raspberry Pi 4 Model B Rev 1.1
PRETTY_NAME="Raspbian GNU/Linux 11 (bullseye)"

Client: Docker Engine - Community
 Version:    27.3.1
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.17.1
    Path:     /usr/libexec/docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.29.7
    Path:     /usr/libexec/docker/cli-plugins/docker-compose
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/SamTV12345/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/SamTV12345/.github/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by SamTV12345** [comment]
How can it be that the access token field is unset? I thought this is standard over all livisi products

**Comment by smike23** [comment]
I dont know. Maybe it has something to do that Livisi discontinued the Cloud servers. Or are not all central units supported? I am using the 1st Generation central unit with Software version 3.1.1111.0.

**Comment by SamTV12345** [comment]
Hm do you use Google chrome? You can right click when you are at the login page in the livisi webapp and click inspect. If you go to the network tab and enter token in the search field you can see a response tab. Click on it and make a screenshot of it. 

![Image](https://github.com/user-attachments/assets/30632fb0-5655-4e18-8bcf-bcdf7ee25180)

**Comment by smike23** [comment]
Yes, i use Chrome, but i don't find a token. Actually i am not sure if this is the correct login screen (see Screenshot attached)

![Image](https://github.com/user-attachments/assets/c7db814f-10ed-4cb7-a2c7-0b239dfe104c)

**Comment by SamTV12345** [comment]
This should be the correct login screen. After login you should get a token in the network tab. It's unfortunately quite hidden. 😅

**Comment by smike23** [comment]
you are right, don't know why i did not find it previously...  now i got it. here is the screenshot

![Image](https://github.com/user-attachments/assets/758418fa-93be-47b7-a204-22307b23ef8d)

**Comment by SamTV12345** [comment]
Could you click on the {;} token entry, go to Response and screenshot? I still can't believe why there should not be an access token field. Otherwise I need to rewrite my logic. I only have SHC2

**Comment by smike23** [comment]
looks good actually...

![Image](https://github.com/user-attachments/assets/31dc6473-6f1e-477b-93f9-c75517fbe24c)

**Comment by smike23** [comment]
i now tried to change the password (removed special characters *$&). Now i get a different Error (i cut off the token in the "can't connect" line):

```
2025-06-15T20:41:35 ℹ️ - Doing db initialization

thread '<unnamed>' panicked at src/main.rs:269:52:

Can't connect: Url(UnableToConnect("ws://smarthome05.home:9090/events?token=eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJhbGwiLCJleHN..."))

stack backtrace:

   0:   0x9a9b08 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h4be301fc8133f6d1

   1:   0x9e4b60 - core::fmt::write::h9607f026b3a1fe6a

   2:   0x9a58dc - std::io::Write::write_fmt::h6cc50c2b43e7755c

   3:   0x9a9894 - std::sys_common::backtrace::print::h7d813e8ad6243ab9

   4:   0x9ab03c - std::panicking::default_hook::{{closure}}::he30c0de6c2b68bd5

   5:   0x9aac08 - std::panicking::default_hook::h88fee80814bba16a

   6:   0x9ab774 - std::panicking::rust_panic_with_hook::h950c2f91443cd029

   7:   0x9ab41c - std::panicking::begin_panic_handler::{{closure}}::h28ff02395d3563f7

   8:   0x9aa06c - std::sys_common::backtrace::__rust_end_short_backtrace::h5825cb7b2f8c8191

   9:   0x9ab1d4 - rust_begin_unwind

  10:    0x39a8c - core::panicking::panic_fmt::h6604f07ff4b4706d

  11:    0x39f40 - core::result::unwrap_failed::h5d28c59258d941df

  12:   0x15c9ec - std::sys_common::backtrace::__rust_begin_short_backtrace::h6fcf96b7ca22debb

  13:   0x10b568 - core::ops::function::FnOnce::call_once{{vtable.shim}}::h61b26f40b41b4a6f

  14:   0x9af5fc - std::sys::pal::unix::thread::Thread::new::thread_start::h0812c960a3e1b477

thread 'main' panicked at src/api_lib/capability.rs:136:14:

called `Result::unwrap()` on an `Err` value: reqwest::Error { kind: Request, url: Url { scheme: "http", cannot_be_a_base: false, username: "", password: None, host: Some(Domain("smarthome05.home")), port: Some(8080), path: "/capability", query: None, fragment: None }, source: hyper_util::client::legacy::Error(SendRequest, hyper::Error(IncompleteMessage)) }

stack backtrace:

   0:   0x9a9b08 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h4be301fc8133f6d1

   1:   0x9e4b60 - core::fmt::write::h9607f026b3a1fe6a

   2:   0x9a58dc - std::io::Write::write_fmt::h6cc50c2b43e7755c

   3:   0x9a9894 - std::sys_common::backtrace::print::h7d813e8ad6243ab9

   4:   0x9ab03c - std::panicking::default_hook::{{closure}}::he30c0de6c2b68bd5

   5:   0x9aac08 - std::panicking::default_hook::h88fee80814bba16a

   6:   0x9ab774 - std::panicking::rust_panic_with_hook::h950c2f91443cd029

   7:   0x9ab41c - std::panicking::begin_panic_handler::{{closure}}::h28ff02395d3563f7

   8:   0x9aa06c - std::sys_common::backtrace::__rust_end_short_backtrace::h5825cb7b2f8c8191

   9:   0x9ab1d4 - rust_begin_unwind

  10:    0x39a8c - core::panicking::panic_fmt::h6604f07ff4b4706d

  11:    0x39f40 - core::result::unwrap_failed::h5d28c59258d941df

  12:    0xaace8 - api::utils::connection::MemPrefill::do_db_initialization::{{closure}}::h2465a64275ee9cef

  13:    0x9f944 - <tokio::task::local::RunUntil<T> as core::future::future::Future>::poll::h3ea0e4b40d2274c4

  14:   0x146ab0 - tokio::runtime::scheduler::current_thread::Context::enter::h40ebfb37dba56886

  15:   0x118d0c - tokio::runtime::context::set_scheduler::h8e242b31b7ef8c14

  16:   0x145ba4 - tokio::runtime::runtime::Runtime::block_on::hbd8a928e3e4dcb6b

  17:   0x11c038 - api::main::he321d005549e5507

  18:   0x15b9b8 - std::sys_common::backtrace::__rust_begin_short_backtrace::h310ea000f6db98e0

  19:   0x139068 - std::rt::lang_start::{{closure}}::h6259daf99a878131

  20:   0x99c69c - std::rt::lang_start_internal::h11093c4ea0de06dd

  21:   0x11c1a4 - main

```

**Comment by SamTV12345** [comment]
> i now tried to change the password (removed special characters *$&). Now i get a different Error (i cut off the token in the "can't connect" line):
> 
> ```
> 2025-06-15T20:41:35 ℹ️ - Doing db initialization
> 
> thread '<unnamed>' panicked at src/main.rs:269:52:
> 
> Can't connect: Url(UnableToConnect("ws://smarthome05.home:9090/events?token=eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJhbGwiLCJleHN..."))
> 
> stack backtrace:
> 
>    0:   0x9a9b08 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h4be301fc8133f6d1
> 
>    1:   0x9e4b60 - core::fmt::write::h9607f026b3a1fe6a
> 
>    2:   0x9a58dc - std::io::Write::write_fmt::h6cc50c2b43e7755c
> 
>    3:   0x9a9894 - std::sys_common::backtrace::print::h7d813e8ad6243ab9
> 
>    4:   0x9ab03c - std::panicking::default_hook::{{closure}}::he30c0de6c2b68bd5
> 
>    5:   0x9aac08 - std::panicking::default_hook::h88fee80814bba16a
> 
>    6:   0x9ab774 - std::panicking::rust_panic_with_hook::h950c2f91443cd029
> 
>    7:   0x9ab41c - std::panicking::begin_panic_handler::{{closure}}::h28ff02395d3563f7
> 
>    8:   0x9aa06c - std::sys_common::backtrace::__rust_end_short_backtrace::h5825cb7b2f8c8191
> 
>    9:   0x9ab1d4 - rust_begin_unwind
> 
>   10:    0x39a8c - core::panicking::panic_fmt::h6604f07ff4b4706d
> 
>   11:    0x39f40 - core::result::unwrap_failed::h5d28c59258d941df
> 
>   12:   0x15c9ec - std::sys_common::backtrace::__rust_begin_short_backtrace::h6fcf96b7ca22debb
> 
>   13:   0x10b568 - core::ops::function::FnOnce::call_once{{vtable.shim}}::h61b26f40b41b4a6f
> 
>   14:   0x9af5fc - std::sys::pal::unix::thread::Thread::new::thread_start::h0812c960a3e1b477
> 
> thread 'main' panicked at src/api_lib/capability.rs:136:14:
> 
> called `Result::unwrap()` on an `Err` value: reqwest::Error { kind: Request, url: Url { scheme: "http", cannot_be_a_base: false, username: "", password: None, host: Some(Domain("smarthome05.home")), port: Some(8080), path: "/capability", query: None, fragment: None }, source: hyper_util::client::legacy::Error(SendRequest, hyper::Error(IncompleteMessage)) }
> 
> stack backtrace:
> 
>    0:   0x9a9b08 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h4be301fc8133f6d1
> 
>    1:   0x9e4b60 - core::fmt::write::h9607f026b3a1fe6a
> 
>    2:   0x9a58dc - std::io::Write::write_fmt::h6cc50c2b43e7755c
> 
>    3:   0x9a9894 - std::sys_common::backtrace::print::h7d813e8ad6243ab9
> 
>    4:   0x9ab03c - std::panicking::default_hook::{{closure}}::he30c0de6c2b68bd5
> 
>    5:   0x9aac08 - std::panicking::default_hook::h88fee80814bba16a
> 
>    6:   0x9ab774 - std::panicking::rust_panic_with_hook::h950c2f91443cd029
> 
>    7:   0x9ab41c - std::panicking::begin_panic_handler::{{closure}}::h28ff02395d3563f7
> 
>    8:   0x9aa06c - std::sys_common::backtrace::__rust_end_short_backtrace::h5825cb7b2f8c8191
> 
>    9:   0x9ab1d4 - rust_begin_unwind
> 
>   10:    0x39a8c - core::panicking::panic_fmt::h6604f07ff4b4706d
> 
>   11:    0x39f40 - core::result::unwrap_failed::h5d28c59258d941df
> 
>   12:    0xaace8 - api::utils::connection::MemPrefill::do_db_initialization::{{closure}}::h2465a64275ee9cef
> 
>   13:    0x9f944 - <tokio::task::local::RunUntil<T> as core::future::future::Future>::poll::h3ea0e4b40d2274c4
> 
>   14:   0x146ab0 - tokio::runtime::scheduler::current_thread::Context::enter::h40ebfb37dba56886
> 
>   15:   0x118d0c - tokio::runtime::context::set_scheduler::h8e242b31b7ef8c14
> 
>   16:   0x145ba4 - tokio::runtime::runtime::Runtime::block_on::hbd8a928e3e4dcb6b
> 
>   17:   0x11c038 - api::main::he321d005549e5507
> 
>   18:   0x15b9b8 - std::sys_common::backtrace::__rust_begin_short_backtrace::h310ea000f6db98e0
> 
>   19:   0x139068 - std::rt::lang_start::{{closure}}::h6259daf99a878131
> 
>   20:   0x99c69c - std::rt::lang_start_internal::h11093c4ea0de06dd
> 
>   21:   0x11c1a4 - main
> ```

You could try again if you'd like to. I updated a bunch of stuff in the ui and backend.
